# Generated by Django 4.0.4 on 2022-05-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0002_equipo_musico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='país',
            new_name='pais',
        ),
    ]
